Add support for publishing new custom votings
lblod/notulen-prepublish-service pull request #115
Opened 2024-10-17 08:39 UTC by lagartoverde

Made it possible to publish the new custom votes generated in GN
Related to this https://github.com/lblod/frontend-gelinkt-notuleren/pull/732

2024-10-20 12:29 UTC, abeforgit requested changes

2024-10-21 08:03 UTC, lagartoverde commented on models/custom-vote.js
> +    this.isCustomVote = true;
Ahhhh yes, that's something I wanted to ask, I didn't find a way of doing the (eq this.type "customVote) or something similar in handlebars, so I created these properties. Is there a way of doing that?
And I thought I didn't wanted just to have isCustomVote and isStandardVote so I kept the type property

2024-10-21 13:27 UTC, lagartoverde commented on models/versioned-notulen.js
> -      console.log(binding);
Is a deletion :)

2024-10-22 12:14 UTC, abeforgit commented on models/versioned-notulen.js
> -      console.log(binding);
cool turns out I'm blind :)

2024-10-22 12:15 UTC, abeforgit commented on models/custom-vote.js
> +    this.isCustomVote = true;
hmm I'll have a look, but at a minimum you could calculate the boolean at the point of passing the context to the template instead of storing it here

2024-10-22 12:18 UTC, abeforgit commented on models/custom-vote.js
> +    this.isCustomVote = true;
you can define your own helpers like this: https://handlebarsjs.com/guide/expressions.html#helpers

2024-11-12 12:37 UTC, merged