Feature/cleanup
lblod/notulen-prepublish-service pull request #14
Opened 2021-01-04 09:26 UTC by lagartoverde

2021-01-04 12:42 UTC, lagartoverde commented
This PR solves
https://binnenland.atlassian.net/browse/GN-1972?atlOrigin=eyJpIjoiMmE1ZTY2NzNiZjA3NDM3YmE5NDY0ZjU1MGZlZjg3MTQiLCJwIjoiaiJ9
https://binnenland.atlassian.net/browse/GN-1973?atlOrigin=eyJpIjoiYzg4NmUxYzYxMjM0NDVhY2ExNTQ4YWUxNmVmZDVhMmQiLCJwIjoiaiJ9

And cleans a little bit the code removing all the functions are files that are not used in the new flow

2021-01-08 09:15 UTC, nvdk requested changes
some small things to fix

2021-01-08 09:15 UTC, nvdk commented on support/notulen-queries.js
> +          prov:startedAtTime ?startedAt;
probably best to wrap each of these in an optional statement as each of them can be missing

2021-01-08 09:15 UTC, nvdk commented on support/behandeling-exporter.js
> +import {handleVersionedResource, hackedSparqlEscapeString} from './pre-importer';;
double semi

2021-01-08 10:19 UTC, merged