Refactor/clean up routes
lblod/notulen-prepublish-service pull request #27
Opened 2021-05-24 11:20 UTC by nvdk

This refactors the routes a bit moving them into separate files split on the provided function (preview, signing, publication). which should give us a better overview. I could also have split on the type of publication (agenda, decision list, etc.) but this seems to make more sense atm.

depends on #26

2021-05-24 11:22 UTC, nvdk commented on README.md
> +Once a specific document is generated for signing or publication the content is "locked". The prepublish service will always reuse the previously generated document for new signatures or publications
should update the TODO after we've verified (and document) how the notulen publication works

2021-05-24 11:23 UTC, nvdk commented on app.js
> +app.use(previewRouter);
probably best if this approach also works in a newer javascript template

2021-05-25 05:07 UTC, Asergey91 requested changes
I have tested with mu-js template 1.5.0 beta 2 and everything seems to work, might as well bump the js template.

2021-05-25 05:07 UTC, Asergey91 commented on routes/publication.js
> +import {getZittingForBesluitenlijst} from '../support/besluit-queries';
this seems to be missing an import 
`import {getZittingForAgenda} from "../support/agenda-queries";`

2021-05-25 09:41 UTC, nvdk commented
rebased branch onto master

2021-05-25 10:11 UTC, abeforgit commented
this doesn't build for me
```
SyntaxError: /usr/src/app/app/node_modules/mkdirp/bin/cmd.js: 'return' outside of function. (13:4)

  11 | if (argv.help) {
  12 |     fs.createReadStream(__dirname + '/usage.txt').pipe(process.stdout);
> 13 |     return;
     |     ^
  14 | }
  15 |
  16 | var paths = argv._.slice();
    at Parser._raise (/usr/src/app/node_modules/@babel/parser/lib/index.js:807:17)
    at Parser.raiseWithData (/usr/src/app/node_modules/@babel/parser/lib/index.js:800:17)
    at Parser.raise (/usr/src/app/node_modules/@babel/parser/lib/index.js:761:17)
    at Parser.parseReturnStatement (/usr/src/app/node_modules/@babel/parser/lib/index.js:12835:12)
    at Parser.parseStatementContent (/usr/src/app/node_modules/@babel/parser/lib/index.js:12513:21)
    at Parser.parseStatement (/usr/src/app/node_modules/@babel/parser/lib/index.js:12465:17)
    at Parser.parseBlockOrModuleBlockBody (/usr/src/app/node_modules/@babel/parser/lib/index.js:13054:25)
    at Parser.parseBlockBody (/usr/src/app/node_modules/@babel/parser/lib/index.js:13045:10)
    at Parser.parseBlock (/usr/src/app/node_modules/@babel/parser/lib/index.js:13029:10)
    at Parser.parseStatementContent (/usr/src/app/node_modules/@babel/parser/lib/index.js:12541:21) {
  loc: Position { line: 13, column: 4 },
  pos: 313,
  code: 'BABEL_PARSE_ERROR',
  reasonCode: 'IllegalReturn'
}
The command '/bin/sh -c /usr/src/app/build-production.sh' returned a non-zero code: 1
ERROR: Service 'preimporter' failed to build : Build failed
```

2021-05-25 10:43 UTC, nvdk commented
> this doesn't build for me

hmm must admin I bumped the template without checking, will have a look later today.

2021-05-25 10:55 UTC, nvdk commented
@abeforgit I've reverted to template bump and it now builds correctly for me

2021-05-25 11:12 UTC, abeforgit commented
the force push tripped me up for a bit fyi

2021-05-25 11:12 UTC, abeforgit commented
the force push tripped me up for a bit fyi

2021-05-25 11:20 UTC, abeforgit approved these changes
seems to work
appreciate the split

2021-05-25 11:59 UTC, merged