Feature/file upload
lblod/notulen-prepublish-service pull request #53
Opened 2021-07-14 15:48 UTC by lagartoverde

2021-07-14 15:51 UTC, lagartoverde commented
I have a linting error on editor-document for the indentation, I understand why the error, but I think that's the correct indentation for that block, what can we do about that rule?

2021-07-16 07:21 UTC, nvdk requested changes
- a small issue with the html output I think 
-  could you add some tests for the attachments so we know for sure that they are annotated correctly?
- still some linting issues in editor-document.js

2021-07-16 07:21 UTC, nvdk commented on support/editor-document.js
> +  return dom.window.document.body.outerHTML;
you'll want innerHTML here I assume? outerHTML will include the body tag

2021-07-16 19:02 UTC, nvdk commented
@lagartoverde small reminder to use a handlebars template for the attachments

2021-07-16 19:04 UTC, lagartoverde commented
Totally missed it, sorry crazy day for me, it will be the first thing I do in Monday

2021-07-19 14:02 UTC, nvdk approved these changes

2021-07-19 14:03 UTC, merged